#!/usr/bin/env python3
"""
Technical Indicators -- SALVAGED VERBATIM, DO NOT EDIT.

Provenance: mexc-trading-bot @ bb87e03, src/indicators.py (675 LOC).
Copied unchanged on purpose. This file is the DEFENDANT: it is the strategy
alpha-gate was built to put on trial, and editing it would be exactly the
quiet-tweak-after-a-bad-week that prereg.py's code hash exists to catch.

If you want different indicator behaviour, do NOT edit this file. Add a new
strategy module, seal it as a new trial, and let the trial counter rise. That
is the whole discipline: the registry has to know how many times you tried.

check.sh verifies this file's hash against every seal that references it.

Provides:
- RSI (Relative Strength Index)
- MACD (Moving Average Convergence Divergence)
- Bollinger Bands
- RMA (Running Moving Average)
- Fibonacci Levels
- Signal Aggregator

Usage:
    from indicators import TechnicalIndicators

    ti = TechnicalIndicators()
    prices = [...]  # List of closing prices

    rsi = ti.calculate_rsi(prices)
    macd = ti.calculate_macd(prices)
    bb = ti.calculate_bollinger_bands(prices)
    signal = ti.get_aggregated_signal(prices, current_price)
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
from enum import Enum


class Signal(Enum):
    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    HOLD = "HOLD"
    SELL = "SELL"
    STRONG_SELL = "STRONG_SELL"


@dataclass
class IndicatorResult:
    """Container for indicator calculation results"""
    value: float
    signal: Signal
    description: str


@dataclass
class MACDResult:
    """MACD calculation result"""
    macd_line: float
    signal_line: float
    histogram: float
    signal: Signal
    description: str


@dataclass
class BollingerBandsResult:
    """Bollinger Bands calculation result"""
    upper_band: float
    middle_band: float
    lower_band: float
    bandwidth: float
    percent_b: float  # Where price is relative to bands (0-1)
    signal: Signal
    description: str


@dataclass
class AggregatedSignal:
    """Combined signal from all indicators"""
    action: Signal
    confidence: float  # 0-100
    signals: Dict[str, Signal]
    reasons: List[str]


class TechnicalIndicators:
    """
    Technical analysis indicators for crypto trading.

    All methods are designed to work with lists of closing prices,
    with the most recent price at the end of the list.
    """

    def __init__(
        self,
        rsi_period: int = 14,
        macd_fast: int = 12,
        macd_slow: int = 26,
        macd_signal: int = 9,
        bb_period: int = 20,
        bb_std: float = 2.0,
        rma_short: int = 20,
        rma_long: int = 200
    ):
        """
        Initialize with configurable periods.

        Args:
            rsi_period: RSI lookback period (default: 14)
            macd_fast: MACD fast EMA period (default: 12)
            macd_slow: MACD slow EMA period (default: 26)
            macd_signal: MACD signal line period (default: 9)
            bb_period: Bollinger Bands SMA period (default: 20)
            bb_std: Bollinger Bands standard deviation multiplier (default: 2.0)
            rma_short: Short RMA period for trend (default: 20)
            rma_long: Long RMA period for trend (default: 200)
        """
        self.rsi_period = rsi_period
        self.macd_fast = macd_fast
        self.macd_slow = macd_slow
        self.macd_signal = macd_signal
        self.bb_period = bb_period
        self.bb_std = bb_std
        self.rma_short = rma_short
        self.rma_long = rma_long

    # -------------------------------------------------------------------------
    # RSI (Relative Strength Index)
    # -------------------------------------------------------------------------

    def calculate_rsi(self, prices: List[float]) -> IndicatorResult:
        """
        Calculate RSI (Relative Strength Index).

        RSI = 100 - (100 / (1 + RS))
        RS = Average Gain / Average Loss

        Signals:
            RSI < 30: Oversold (BUY)
            RSI > 70: Overbought (SELL)
            30 <= RSI <= 70: Neutral (HOLD)

        Args:
            prices: List of closing prices (most recent last)

        Returns:
            IndicatorResult with RSI value and signal
        """
        if len(prices) < self.rsi_period + 1:
            return IndicatorResult(50.0, Signal.HOLD, "Insufficient data for RSI")

        df = pd.DataFrame(prices, columns=["close"])
        delta = df["close"].diff()

        gain = delta.where(delta > 0, 0)
        loss = -delta.where(delta < 0, 0)

        avg_gain = gain.rolling(window=self.rsi_period).mean()
        avg_loss = loss.rolling(window=self.rsi_period).mean()

        rs = avg_gain / avg_loss.replace(0, np.inf)
        rsi = 100 - (100 / (1 + rs))

        rsi_value = float(rsi.iloc[-1]) if not pd.isna(rsi.iloc[-1]) else 50.0

        # Determine signal
        if rsi_value < 20:
            signal = Signal.STRONG_BUY
            desc = f"RSI {rsi_value:.1f} - Extremely oversold"
        elif rsi_value < 30:
            signal = Signal.BUY
            desc = f"RSI {rsi_value:.1f} - Oversold"
        elif rsi_value > 80:
            signal = Signal.STRONG_SELL
            desc = f"RSI {rsi_value:.1f} - Extremely overbought"
        elif rsi_value > 70:
            signal = Signal.SELL
            desc = f"RSI {rsi_value:.1f} - Overbought"
        else:
            signal = Signal.HOLD
            desc = f"RSI {rsi_value:.1f} - Neutral"

        return IndicatorResult(rsi_value, signal, desc)

    # -------------------------------------------------------------------------
    # MACD (Moving Average Convergence Divergence)
    # -------------------------------------------------------------------------

    def calculate_macd(self, prices: List[float]) -> MACDResult:
        """
        Calculate MACD (Moving Average Convergence Divergence).

        MACD Line = 12-period EMA - 26-period EMA
        Signal Line = 9-period EMA of MACD Line
        Histogram = MACD Line - Signal Line

        Signals:
            MACD crosses above Signal: BUY
            MACD crosses below Signal: SELL
            Histogram positive and growing: Bullish momentum
            Histogram negative and shrinking: Bearish momentum

        Args:
            prices: List of closing prices (most recent last)

        Returns:
            MACDResult with MACD components and signal
        """
        min_periods = self.macd_slow + self.macd_signal
        if len(prices) < min_periods:
            return MACDResult(
                0.0, 0.0, 0.0, Signal.HOLD,
                "Insufficient data for MACD"
            )

        df = pd.DataFrame(prices, columns=["close"])

        # Calculate EMAs
        ema_fast = df["close"].ewm(span=self.macd_fast, adjust=False).mean()
        ema_slow = df["close"].ewm(span=self.macd_slow, adjust=False).mean()

        # MACD Line
        macd_line = ema_fast - ema_slow

        # Signal Line
        signal_line = macd_line.ewm(span=self.macd_signal, adjust=False).mean()

        # Histogram
        histogram = macd_line - signal_line

        macd_val = float(macd_line.iloc[-1])
        signal_val = float(signal_line.iloc[-1])
        hist_val = float(histogram.iloc[-1])

        # Previous values for crossover detection
        prev_macd = float(macd_line.iloc[-2]) if len(macd_line) > 1 else macd_val
        prev_signal = float(signal_line.iloc[-2]) if len(signal_line) > 1 else signal_val
        prev_hist = float(histogram.iloc[-2]) if len(histogram) > 1 else hist_val

        # Determine signal
        # Bullish crossover: MACD crosses above signal
        if prev_macd <= prev_signal and macd_val > signal_val:
            signal = Signal.BUY
            desc = "MACD bullish crossover"
        # Bearish crossover: MACD crosses below signal
        elif prev_macd >= prev_signal and macd_val < signal_val:
            signal = Signal.SELL
            desc = "MACD bearish crossover"
        # Strong bullish: histogram positive and growing
        elif hist_val > 0 and hist_val > prev_hist:
            signal = Signal.BUY
            desc = f"MACD histogram positive ({hist_val:.6f}) and growing"
        # Strong bearish: histogram negative and shrinking
        elif hist_val < 0 and hist_val < prev_hist:
            signal = Signal.SELL
            desc = f"MACD histogram negative ({hist_val:.6f}) and falling"
        # Weakening bullish
        elif hist_val > 0 and hist_val < prev_hist:
            signal = Signal.HOLD
            desc = "MACD bullish but weakening"
        # Weakening bearish
        elif hist_val < 0 and hist_val > prev_hist:
            signal = Signal.HOLD
            desc = "MACD bearish but recovering"
        else:
            signal = Signal.HOLD
            desc = f"MACD neutral (histogram: {hist_val:.6f})"

        return MACDResult(macd_val, signal_val, hist_val, signal, desc)

    # -------------------------------------------------------------------------
    # Bollinger Bands
    # -------------------------------------------------------------------------

    def calculate_bollinger_bands(
        self,
        prices: List[float],
        current_price: Optional[float] = None
    ) -> BollingerBandsResult:
        """
        Calculate Bollinger Bands.

        Middle Band = 20-period SMA
        Upper Band = Middle Band + (2 × standard deviation)
        Lower Band = Middle Band - (2 × standard deviation)

        %B = (Price - Lower Band) / (Upper Band - Lower Band)
        Bandwidth = (Upper Band - Lower Band) / Middle Band

        Signals:
            Price at/below lower band + low %B: BUY (oversold)
            Price at/above upper band + high %B: SELL (overbought)
            Band squeeze (low bandwidth): Breakout incoming

        Args:
            prices: List of closing prices (most recent last)
            current_price: Current price to evaluate (defaults to last price)

        Returns:
            BollingerBandsResult with band values and signal
        """
        if len(prices) < self.bb_period:
            return BollingerBandsResult(
                0.0, 0.0, 0.0, 0.0, 0.5, Signal.HOLD,
                "Insufficient data for Bollinger Bands"
            )

        df = pd.DataFrame(prices, columns=["close"])

        # Middle band (SMA)
        middle_band = df["close"].rolling(window=self.bb_period).mean()

        # Standard deviation
        std = df["close"].rolling(window=self.bb_period).std()

        # Upper and lower bands
        upper_band = middle_band + (std * self.bb_std)
        lower_band = middle_band - (std * self.bb_std)

        upper_val = float(upper_band.iloc[-1])
        middle_val = float(middle_band.iloc[-1])
        lower_val = float(lower_band.iloc[-1])

        price = current_price if current_price is not None else prices[-1]

        # Calculate %B (where price is relative to bands)
        band_range = upper_val - lower_val
        if band_range > 0:
            percent_b = (price - lower_val) / band_range
        else:
            percent_b = 0.5

        # Calculate bandwidth (volatility measure)
        if middle_val > 0:
            bandwidth = band_range / middle_val
        else:
            bandwidth = 0.0

        # Determine signal
        if percent_b <= 0:
            signal = Signal.STRONG_BUY
            desc = f"Price below lower band (%B: {percent_b:.2f})"
        elif percent_b < 0.2:
            signal = Signal.BUY
            desc = f"Price near lower band (%B: {percent_b:.2f})"
        elif percent_b >= 1.0:
            signal = Signal.STRONG_SELL
            desc = f"Price above upper band (%B: {percent_b:.2f})"
        elif percent_b > 0.8:
            signal = Signal.SELL
            desc = f"Price near upper band (%B: {percent_b:.2f})"
        else:
            signal = Signal.HOLD
            desc = f"Price within bands (%B: {percent_b:.2f})"

        return BollingerBandsResult(
            upper_val, middle_val, lower_val,
            bandwidth, percent_b, signal, desc
        )

    # -------------------------------------------------------------------------
    # RMA (Running Moving Average) for Trend
    # -------------------------------------------------------------------------

    def calculate_rma(self, prices: List[float], period: int) -> Optional[float]:
        """
        Calculate RMA (Running Moving Average / Wilder's smoothing).

        Args:
            prices: List of closing prices
            period: RMA period

        Returns:
            RMA value or None if insufficient data
        """
        if len(prices) < period:
            return None

        series = pd.Series(prices)
        alpha = 1 / period
        return float(series.ewm(alpha=alpha, adjust=False).mean().iloc[-1])

    def get_trend(self, prices: List[float]) -> Tuple[Signal, str]:
        """
        Determine trend using RMA 20/200 crossover.

        Args:
            prices: List of closing prices

        Returns:
            Tuple of (Signal, description)
        """
        rma_short = self.calculate_rma(prices, self.rma_short)
        rma_long = self.calculate_rma(prices, self.rma_long)

        if rma_short is None or rma_long is None:
            return Signal.HOLD, "Insufficient data for trend"

        if rma_short > rma_long * 1.02:  # 2% above
            return Signal.BUY, f"Bullish trend (RMA{self.rma_short} > RMA{self.rma_long})"
        elif rma_short < rma_long * 0.98:  # 2% below
            return Signal.SELL, f"Bearish trend (RMA{self.rma_short} < RMA{self.rma_long})"
        else:
            return Signal.HOLD, f"Neutral trend (RMAs converging)"

    # -------------------------------------------------------------------------
    # Fibonacci Levels
    # -------------------------------------------------------------------------

    def calculate_fibonacci_levels(
        self,
        prices: List[float],
        lookback: int = 100
    ) -> Dict[str, float]:
        """
        Calculate Fibonacci retracement levels from recent high/low.

        Args:
            prices: List of closing prices
            lookback: Number of periods to look back for high/low

        Returns:
            Dictionary of Fibonacci levels
        """
        if len(prices) < lookback:
            lookback = len(prices)

        recent_prices = prices[-lookback:]
        high = max(recent_prices)
        low = min(recent_prices)
        diff = high - low

        return {
            "0.0%": high,
            "23.6%": high - diff * 0.236,
            "38.2%": high - diff * 0.382,
            "50.0%": high - diff * 0.500,
            "61.8%": high - diff * 0.618,
            "78.6%": high - diff * 0.786,
            "100%": low,
            "high": high,
            "low": low
        }

    def get_nearest_fib_level(
        self,
        current_price: float,
        fib_levels: Dict[str, float]
    ) -> Tuple[str, float, str]:
        """
        Find the nearest Fibonacci level to current price.

        Args:
            current_price: Current price
            fib_levels: Dictionary of Fibonacci levels

        Returns:
            Tuple of (level_name, level_price, position)
        """
        levels = {k: v for k, v in fib_levels.items() if k not in ["high", "low"]}

        nearest_name = "50.0%"
        nearest_dist = float('inf')

        for name, price in levels.items():
            dist = abs(current_price - price)
            if dist < nearest_dist:
                nearest_dist = dist
                nearest_name = name

        level_price = levels[nearest_name]

        if current_price > level_price:
            position = "above"
        elif current_price < level_price:
            position = "below"
        else:
            position = "at"

        return nearest_name, level_price, position

    # -------------------------------------------------------------------------
    # Aggregated Signal
    # -------------------------------------------------------------------------

    def get_aggregated_signal(
        self,
        prices: List[float],
        current_price: Optional[float] = None,
        weights: Optional[Dict[str, float]] = None
    ) -> AggregatedSignal:
        """
        Combine all indicators into a single trading signal with confidence.

        Default weights:
            RSI: 25%
            MACD: 25%
            Bollinger Bands: 25%
            Trend (RMA): 25%

        Args:
            prices: List of closing prices
            current_price: Current price (defaults to last price)
            weights: Custom weights for each indicator

        Returns:
            AggregatedSignal with action, confidence, and reasoning
        """
        if weights is None:
            weights = {
                "rsi": 0.25,
                "macd": 0.25,
                "bollinger": 0.25,
                "trend": 0.25
            }

        if current_price is None:
            current_price = prices[-1] if prices else 0.0

        # Calculate all indicators
        rsi = self.calculate_rsi(prices)
        macd = self.calculate_macd(prices)
        bb = self.calculate_bollinger_bands(prices, current_price)
        trend_signal, trend_desc = self.get_trend(prices)

        signals = {
            "rsi": rsi.signal,
            "macd": macd.signal,
            "bollinger": bb.signal,
            "trend": trend_signal
        }

        reasons = [rsi.description, macd.description, bb.description, trend_desc]

        # Convert signals to numeric scores
        def signal_to_score(sig: Signal) -> float:
            scores = {
                Signal.STRONG_BUY: 1.0,
                Signal.BUY: 0.5,
                Signal.HOLD: 0.0,
                Signal.SELL: -0.5,
                Signal.STRONG_SELL: -1.0
            }
            return scores.get(sig, 0.0)

        # Calculate weighted score
        weighted_score = (
            signal_to_score(rsi.signal) * weights["rsi"] +
            signal_to_score(macd.signal) * weights["macd"] +
            signal_to_score(bb.signal) * weights["bollinger"] +
            signal_to_score(trend_signal) * weights["trend"]
        )

        # Count agreeing signals
        buy_signals = sum(1 for s in signals.values() if s in [Signal.BUY, Signal.STRONG_BUY])
        sell_signals = sum(1 for s in signals.values() if s in [Signal.SELL, Signal.STRONG_SELL])

        # Determine action and confidence
        if weighted_score >= 0.5:
            action = Signal.STRONG_BUY
            confidence = min(95, 60 + (buy_signals * 10))
        elif weighted_score >= 0.25:
            action = Signal.BUY
            confidence = min(85, 50 + (buy_signals * 10))
        elif weighted_score <= -0.5:
            action = Signal.STRONG_SELL
            confidence = min(95, 60 + (sell_signals * 10))
        elif weighted_score <= -0.25:
            action = Signal.SELL
            confidence = min(85, 50 + (sell_signals * 10))
        else:
            action = Signal.HOLD
            confidence = 50 - abs(weighted_score * 20)

        return AggregatedSignal(action, confidence, signals, reasons)


# Convenience functions for direct use
def get_trading_signal(
    prices: List[float],
    current_price: Optional[float] = None
) -> Tuple[str, float, List[str]]:
    """
    Get a simple trading signal from price data.

    Args:
        prices: List of closing prices
        current_price: Current price (optional)

    Returns:
        Tuple of (action, confidence, reasons)
        action: "BUY", "SELL", or "HOLD"
        confidence: 0-100
        reasons: List of indicator descriptions
    """
    ti = TechnicalIndicators()
    result = ti.get_aggregated_signal(prices, current_price)

    action_map = {
        Signal.STRONG_BUY: "BUY",
        Signal.BUY: "BUY",
        Signal.HOLD: "HOLD",
        Signal.SELL: "SELL",
        Signal.STRONG_SELL: "SELL"
    }

    return action_map[result.action], result.confidence, result.reasons


if __name__ == "__main__":
    # Test with sample data
    import requests

    print("Testing Technical Indicators Module")
    print("=" * 50)

    # Fetch sample data from MEXC
    symbol = "FLRUSDT"
    url = f"https://api.mexc.com/api/v3/klines?symbol={symbol}&interval=1m&limit=300"

    try:
        resp = requests.get(url, timeout=10)
        data = resp.json()
        prices = [float(candle[4]) for candle in data]  # Close prices

        print(f"\nFetched {len(prices)} price points for {symbol}")
        print(f"Current price: ${prices[-1]:.6f}")

        ti = TechnicalIndicators()

        # Test individual indicators
        print("\n--- Individual Indicators ---")

        rsi = ti.calculate_rsi(prices)
        print(f"\nRSI: {rsi.value:.2f}")
        print(f"Signal: {rsi.signal.value}")
        print(f"Description: {rsi.description}")

        macd = ti.calculate_macd(prices)
        print(f"\nMACD Line: {macd.macd_line:.8f}")
        print(f"Signal Line: {macd.signal_line:.8f}")
        print(f"Histogram: {macd.histogram:.8f}")
        print(f"Signal: {macd.signal.value}")
        print(f"Description: {macd.description}")

        bb = ti.calculate_bollinger_bands(prices)
        print(f"\nBollinger Bands:")
        print(f"Upper: ${bb.upper_band:.6f}")
        print(f"Middle: ${bb.middle_band:.6f}")
        print(f"Lower: ${bb.lower_band:.6f}")
        print(f"%B: {bb.percent_b:.2f}")
        print(f"Signal: {bb.signal.value}")
        print(f"Description: {bb.description}")

        trend_signal, trend_desc = ti.get_trend(prices)
        print(f"\nTrend: {trend_signal.value}")
        print(f"Description: {trend_desc}")

        # Test aggregated signal
        print("\n--- Aggregated Signal ---")
        result = ti.get_aggregated_signal(prices)
        print(f"\nAction: {result.action.value}")
        print(f"Confidence: {result.confidence:.1f}%")
        print(f"\nSignals by indicator:")
        for name, sig in result.signals.items():
            print(f"  {name}: {sig.value}")
        print(f"\nReasons:")
        for reason in result.reasons:
            print(f"  - {reason}")

    except Exception as e:
        print(f"Error testing: {e}")
        print("\nRunning with synthetic data instead...")

        # Synthetic test data
        import random
        prices = [0.01 + random.uniform(-0.001, 0.001) for _ in range(300)]

        ti = TechnicalIndicators()
        result = ti.get_aggregated_signal(prices)
        print(f"\nAction: {result.action.value}")
        print(f"Confidence: {result.confidence:.1f}%")
